host: "127.0.0.1"
port: 18317
remote-management:
  allow-remote: true
  secret-key: "$2a$10$gqCHtrticC0hJ2q40bCwNu1BkH1a83Tp60IAk0ANr/0l95sTiaBwO"
  disable-control-panel: false
auth-dir: "auths"
api-keys:
  - "local-test-key"
debug: true
local-model: true
codex-api-key:
  - api-key: sk-sp-78099a8e28374bbfa9a8e2d6338bf653
    request-mode: chat
    base-url: https://coding.dashscope.aliyuncs.com/v1
    proxy-url: ""
    models:
      - name: qwen3.6-plus
        alias: gpt-5.5
      - name: qwen3.6-plus
        alias: gpt-5.4
      - name: glm-5
        alias: gpt-5.3-codex
      - name: kimi-k2.5
        alias: gpt-image-2
      - name: MiniMax-M2.5
        alias: gpt-5.4-mini
redis-usage-queue-retention-seconds: 60
claude-api-key:
  - api-key: sk-sp-78099a8e28374bbfa9a8e2d6338bf653
    base-url: https://coding.dashscope.aliyuncs.com/apps/anthropic
    models:
      - name: qwen3.6-plus
        alias: claude-opus-4-7
      - name: qwen3.6-plus
        alias: claude-sonnet-4-6
      - name: glm-5
        alias: claude-opus-4-6
